demo:
  window_title: Speech Recognition
  frame_buffer_size: 10
  text_rel_pos_x: 0.5
  text_rel_pos_y: 0.9
  max_line_len: 30    # Break lines longer than ``max_line_len``. null to disable.
  api_keypoints: http://158.109.8.116:8000/face_keypoints/